blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import blog_redirect

urlpatterns = [
    path('luga_admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('news.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/news/urls.py
from django.urls import path
from . import views
from .views import SearchView

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('tag/<int:pk>/', views.tag_detail, name='tag_detail'),
    path('tags/', views.tags_list, name='tags_list'),
    path('categories/', views.categories_list, name='categories_list'),
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
    path('search/', SearchView.as_view(), name='search_view'),
    path('detail/<int:pk>', views.news_detail, name='news_detail'),

]

blog/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class News(models.Model):
    user = models.ForeignKey(User, verbose_name='Автор',
                             on_delete=models.CASCADE,)
    title = models.CharField(max_length=150, verbose_name='Заголовок',
                             db_index=True)
    text = models.TextField(max_length=None, verbose_name='Текст статті',
                            blank=True)
    image = models.ImageField(upload_to='img', blank=True, null=True,
                              verbose_name='Картинка')
    created = models.DateTimeField(verbose_name='Дата створення',
                                   auto_now_add=True)
    description = models.CharField(verbose_name='Опис', max_length=150,
                                   blank=True)
    keywords = models.CharField(verbose_name='Ключові слова', max_length=350,
                                blank=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='tags')
    category = models.ForeignKey("Category", on_delete=models.SET_NULL,
                                 verbose_name='Категорія',
                                 blank=True, null=True, related_name="category")
    published = models.BooleanField(default=True, verbose_name='Опубліковано')

    class Meta:
        verbose_name = 'Стаття'
        verbose_name_plural = 'Статті'
        ordering = ['-created']

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Назва')

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'
        ordering = ['title']

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=150, verbose_name='Тег')

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Тегі'
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tags_detail', kwargs={'pk': self.pk})


class Comments(models.Model):
    user = models.ForeignKey(User, verbose_name='Коментатор',
                             on_delete=models.CASCADE)
    new = models.ForeignKey(News, verbose_name='Новина',
                            on_delete=models.CASCADE)
    text = models.TextField(max_length=None, verbose_name='Коментар',
                            blank=True)
    created = models.DateTimeField(verbose_name='Дата створення',
                                   auto_now_add=True)
    moderation = models.BooleanField(default=False,
                                     verbose_name='Можливість редагувати')

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['-created']

    def __str__(self):
        return '{}'.format(self.user)

blog/news/forms.py
from django.forms import ModelForm
from .models import Comments


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('text',)

blog/blog/views.py
from django.http import HttpResponse
from  django.shortcuts import redirect

def blog_redirect(request):
    return redirect(news_list, permanent=True)

blog/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import CommentForm
from django.db.models import Q, CharField, TextField
from django.db.models.functions import Lower
from django.views import View

# Create your views here.


def news_list(request):
    news = News.objects.filter(published=True)
    return render(request, 'news/news_list.html', {'news': news})


def categories_list(request):
    categories = Category.objects.all()
    return render(request, 'news/categories_list.html', {'categories': categories})


def category_detail(request, pk):
    category = Category.objects.get(id=pk)
    return render(request, 'news/category_detail.html', {'category': category})


def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'news/tags_list.html', {'tags': tags})


def tag_detail(request, pk):
    tag = Tag.objects.get(id=pk)
    return render(request, 'news/tag_detail.html', {'tag': tag})


def news_detail(request, pk):
    new = get_object_or_404(News, id=pk)
    comment = Comments.objects.filter(new=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.new = new
            form.save()
            return redirect(news_detail, pk)
    else:

        form = CommentForm()
    return render(request, 'news/news_detail.html',
                  {'new': new, 'comments': comment, 'form': form})


class SearchView(View):
    CharField.register_lookup(Lower, "lower")
    TextField.register_lookup(Lower, "lower")
    template_name = 'news/search.html'

    def get(self, request, *args, **kwargs):
        search_query = request.GET.get('search', '')
        print(search_query.lower())

        founded_news = News.objects.filter(Q(title__lower__icontains=search_query) |
                                       Q(text__lower__icontains=search_query))
        context = {'founded_news': founded_news}
        return render(self.request, self.template_name, context)

blog/news/templates/news/base_blog.html
{% extends 'base.html' %}

blog/news/templates/news/categories_list.html
{% extends 'news/base_blog.html' %}

{% block title %}
    Категорії
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h4>Методички в категоріях:</h4>
        </div>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded">
        {% for category in categories %}

            <div class="card-body">
                <h5 class="card-title"><b><a href="{% url 'category_detail' pk=category.id %}">{{ category.title }}</a></b></h5>
            </div>
        {% endfor %}
    </div>

{% endblock %}

blog/news/templates/news/category_detail.html
{% extends 'news/base_blog.html' %}

{% block desk %} {{ news.description }} {% endblock desk %}
{% block keywords %} {{ news.keywords }} {% endblock keywords %}

{% block title %}
    {{ category.title }} - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h4>Методички в категорії "{{ category.title|title }}":</h4>
        </div>
    </div>
    {% for new in category.category.all %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card">
                <h6 class="card-header">{{ new.category|default_if_none:'Загальна категорія' }}</h6>
                <div class="card-body">
                    <h5 class="card-title"><b>{{ new.title }}</b></h5>
                    <p class="card-text">{{ new.text|truncatechars:350|safe }}</p>
                    <a href="{% url 'news_detail' pk=new.id %}"
                       class="btn btn-dark" style="float:right;">Читати</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

blog/news/templates/news/news_detail.html
{% extends 'news/base_blog.html' %}

{% block desk %} {{ news.description }} {% endblock desk %}
{% block keywords %} {{ news.keywords }} {% endblock keywords %}

{% block title %}
    {{ new.title }} - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card">
            <h6 class="card-header">{{ new.category|default_if_none:'Загальна категорія' }}</h6>
            <div class="card-body">
                {% if new.image %}
                    <div align="center">
                        <img src="{{ MEDIA_URL }}{{ new.image.url }}"
                             class="img-fluid" alt="Responsive image">
                    </div><br>
                {% endif %}
                <h5 class="card-title"><b>{{ new.title }}</b></h5>
                <p class="card-text">{{ new.text|safe }}</p><br/><br/>
                <p style="font-size:14px" align="right">{{ new.created }}</p>
                <br/>
                <p style="font-size:14px">Тегі - {% for tag in new.tags.all %}
                    {{ tag.title }}
                {% endfor %}</p>
            </div>
        </div>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card mt-5">
            <div class="card-body">
                {% if comments %}
                    Коментарі
                {% else %}
                    Коментарів немає
                {% endif %}
            </div>
        </div>
    </div>


    {% for comment in comments %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card mt-2">
                <h6 class="card-header">
                    <small><b>{{ comment.user }}</b></small>
                </h6>
                <div class="card-body">
                    <p class="card-text">
                        <small>{{ comment.text|safe }}</small>
                    </p>
                    <p style="font-size:9px"
                       align="right">{{ comment.created }}</p>
                </div>
            </div>
        </div>
    {% endfor %}<br> <br>


{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <div class="form-group">#}
{#            <label for="id_text">Написати коментар</label>#}
{#            <textarea class="form-control" name="text" id="id_text"#}
{#                      cols="10" rows="4"></textarea>#}
{#        </div>#}
{#        <button type="submit" class="btn btn-primary">Надіслати</button>#}
{#    </form> <br> <br>#}


{% endblock %}

blog/news/templates/news/news_list.html
{% extends 'news/base_blog.html' %}

{% block title %}
    Методички Луганського
{% endblock %}

{% block content %}
    {% for new in news %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card">
                <h6 class="card-header">{{ new.category|default_if_none:'Загальна категорія' }}</h6>
                <div class="card-body">
                    <h5 class="card-title"><b>{{ new.title }}</b></h5>
                    <p class="card-text">{{ new.text|truncatechars:350|safe }}</p>
                    <a href="{% url 'news_detail' pk=new.id %}"
                       class="btn btn-dark" style="float:right;">Читати</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

blog/news/templates/news/search.html
{% extends 'news/base_blog.html' %}

{% block desk %} {{ news.description }} {% endblock desk %}
{% block keywords %} {{ news.keywords }} {% endblock keywords %}

{% block title %}
    Результати пошуку
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card-body">
                <h4>Знайдено результатів: {{ founded_news.count }}</h4>
            </div>
    </div>

    {% for new in founded_news %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card">
                <h6 class="card-header">{{ new.category|default_if_none:'Загальна категорія' }}</h6>
                <div class="card-body">
                    <h5 class="card-title"><b>{{ new.title }}</b></h5>
                    <p class="card-text">{{ new.text|truncatechars:350|safe }}</p>
                    <a href="{% url 'news_detail' pk=new.id %}"
                       class="btn btn-dark" style="float:right;">Читати</a>
                </div>
            </div>
        </div>
    {% endfor %}


{% endblock %}

blog/news/templates/news/tag_detail.html
{% extends 'news/base_blog.html' %}

{% block desk %} {{ news.description }} {% endblock desk %}
{% block keywords %} {{ news.keywords }} {% endblock keywords %}

{% block title %}
    {{ tag.title }} - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h4>Методички з тегом "{{ tag.title|title }}":</h4>
        </div>
    </div>
    {% for new in tag.tags.all %}
        <div class="shadow p-3 mb-5 bg-white rounded">
            <div class="card">
                <h6 class="card-header">{{ new.category|default_if_none:'Загальна категорія' }}</h6>
                <div class="card-body">
                    <h5 class="card-title"><b>{{ new.title }}</b></h5>
                    <p class="card-text">{{ new.text|truncatechars:350|safe }}</p>
                    <a href="{% url 'news_detail' pk=new.id %}"
                       class="btn btn-dark" style="float:right;">Читати</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

blog/news/templates/news/tags_list.html
{% extends 'news/base_blog.html' %}

{% block title %}
    Tags list
{% endblock %}

{% block content %}
    <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h4>Методички за тегами:</h4>
        </div>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded">
        {% for tag in tags %}

            <div class="card-body">
                <h5 class="card-title"><b><a href="{% url 'tag_detail' pk=tag.id %}">{{ tag.title }}</a></b></h5>
            </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block desk %} {% endblock desk %}">
    <meta name="keywords" content="{% block keywords %} {% endblock keywords %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>
        {% block title %}
            Blog Engine
        {% endblock %}
    </title>
    <style>
        body {
            background: #f4f4f4; /* Цвет фона */
        {#    color: #fc0; /* Цвет текста */#}
        }
    </style>
</head>
<body>
<div class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <a class="navbar-brand" href="/"><img class="img-responsive"
                                              src="{% static 'img/luga_logo.png' %}"
                                              alt="Responsive image"
                                              height="40px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Всі методички <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories_list' %}">Категорії</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tags_list' %}">Тегі</a>
                </li>
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/luga_admin" tabindex="-1"
                           aria-disabled="true">Adminka</a>
                    </li>
                {% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'search_view' %}" method="GET">
                <input class="form-control mr-sm-2" type="search"
                       placeholder="Пошук" aria-label="Search" name="search">
                <button class="btn btn-outline-primary my-2 my-sm-0"
                        type="submit">Пошук
                </button>
            </form>

            <div>
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href="/accounts/logout/">Log Out</a>
                {% else %}
                    <a class="nav-link" href="/accounts/login/">Log In</a>
                {% endif %}
            </div>

        </div>

    </nav>
</div>
<br><br>
<header>
    <img src="{% static 'img/banner.jpg' %}"
         class="img-fluid" alt="Responsive image">
</header>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-9 offset-md-0">
            {% block content %}
                There is no content for you
            {% endblock %}
</body>
</html>